---
- name: Installing basic firmware and libraries for the proxy server!
  hosts: all

  tasks:
    - name: "Update the repositories and upgrade them (apt-get update + apt-get upgrade)"
      shell: sudo apt-get update && sudo apt-get upgrade -y

    - name: "Clone the AWX APM repository"
      git:
        repo: https://github.com/fankp1/AWX_APM.git
        dest: /home/pi/APM_AWX
        clone: yes
        
    - name: "Install the Mosquitto MQTT broker"
      become: yes
      apt:
        name: mosquitto
        state: present

    - name: "Start the Mosquitto MQTT broker"
      become: yes
      shell: sudo systemctl enable mosquitto.service

    - name: "Enable the mosquitto broker service so that is automatically starts after a restart"
      become: yes
      shell: sudo systemctl start mosquitto.service

    - name: "Install NodeJS"
      become: yes
      apt:
        name: nodejs
        state: present

    - name: "Install NPM"
      become: yes
      apt:
        name: npm
        state: present 

    - name: "Install n with npm"
      become: yes
      shell: npm install -g n   
      
    - name: "Install the newest version of Node"
      become: yes
      shell: n latest
      
    - name: "Install Node-RED"
      shell: "bash /home/pi/APM_AWX/node-red.sh --confirm-install --confirm-pi"
      ignore_errors: true
      
    - name: "Start the Node-RED service"
      become: yes
      shell: sudo systemctl start nodered.service

    - name: "Enable the Node-RED service so that is automatically starts after a restart"
      become: yes
      shell: sudo systemctl enable nodered.service

    - name: get service facts
      ansible.builtin.service_facts:

    - name: try to work out how to access the service
      ansible.builtin.debug:
        var: ansible_facts.services["nodered.service"]

  npm install node-red-contrib-revpi-nodes

  sudo apt-get update && sudo apt-get upgrade -y

curl https://repos.influxdata.com/influxdata-archive.key | gpg --dearmor | sudo tee /usr/share/keyrings/influxdb-archive-keyring.gpg >/dev/null

echo "deb [signed-by=/usr/share/keyrings/influxdb-archive-keyring.gpg] https://repos.influxdata.com/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
sudo apt update
sudo apt install influxdb
sudo systemctl unmask influxdb
sudo systemctl enable influxdb
sudo systemctl start influxdb

sudo apt-get update && sudo apt-get upgrade -y
curl https://apt.grafana.com/gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/grafana-archive-keyrings.gpg >/dev/null
echo "deb [signed-by=/usr/share/keyrings/grafana-archive-keyrings.gpg] https://apt.grafana.com stable main" | sudo tee /etc/apt/sources.list.d/grafana.list
sudo apt update
sudo apt install grafana
sudo systemctl enable grafana-server
sudo systemctl start grafana-server


      


