---
- name: Installing basic firmware and libraries for the proxy server!
  hosts: all

  tasks:
    - name: "Update the repositories and upgrade them (apt-get update + apt-get upgrade)"
      shell: sudo apt-get update && sudo apt-get upgrade -y

    - name: "Clone the AWX APM repository"
      git:
        repo: https://github.com/fankp1/AWX_APM.git
        dest: /home/pi/
        clone: yes
        
    - name: "Install the Mosquitto MQTT broker"
      become: yes
      apt:
        name: mosquitto
        state: present

    - name: "Start the Mosquitto MQTT broker"
      become: yes
      shell: sudo systemctl enable mosquitto.service

    - name: "Enable the mosquitto broker service so that is automatically starts after a restart"
      become: yes
      shell: sudo systemctl start mosquitto.service

    - name: "Install NodeJS"
      become: yes
      apt:
        name: nodejs
        state: present

    - name: "Install NPM"
      become: yes
      apt:
        name: npm
        state: present 

    - name: "Install n with npm"
      become: yes
      shell: npm install -g n   
      
    - name: "Install the newest version of Node"
      become: yes
      shell: n latest
      
    - name: "Install Node-RED"
      shell: "bash /home/pi/APM_AWX/nodered.sh --confirm-install --confirm-pi"
      ignore_errors: true
      
    - name: "Start the Node-RED service"
      become: yes
      shell: sudo systemctl start nodered.service

    - name: "Enable the Node-RED service so that is automatically starts after a restart"
      become: yes
      shell: sudo systemctl enable nodered.service
      


