---
- name: Installing basic firmware and libraries for the proxy server!
  hosts: all

  tasks:
    - name: "Update the repositories and upgrade them (apt-get update + apt-get upgrade)"
      shell: sudo apt-get update && sudo apt-get upgrade -y

    - name: "Install the Mosquitto MQTT broker"
      become: yes
      apt:
        name: mosquitto
        state: present

    - name: "Start the Mosquitto MQTT broker"
      become: yes
      shell: sudo systemctl enable mosquitto.service

    - name: "Enable the mosquitto broker service so that is automatically starts after a restart"
      become: yes
      shell: sudo systemctl start mosquitto.service

    - name: "Update NodeJS to the newest version"
      become: yes
      shell: sudo n latest
      
    - name: "Install relevant packages and libraries"
      shell: "bash < <(curl -sL https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered) --confirm-pi --confirm-install"
 
    - name: "Start the Node-RED service"
      become: yes
      shell: sudo systemctl start nodered.service

    - name: "Enable the Node-RED service so that is automatically starts after a restart"
      become: yes
      shell: sudo systemctl enable nodered.service

