---
- name: Hello World!
  hosts: all

  tasks:
    - name: "Update repositories cache 'apt-get update'"
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Hello World!
      shell: sudo apt-get update && sudo apt-get upgrade -y

    - name: Install the Mosquitto broker
      apt:
        name: mosquitoo
        state: present

    - name: Set new version number
      copy:
        content: "1.0.1"
        dest: /etc/fogdevice/version
