---
- name: Hello World!
  hosts: all

  tasks:
    - name: "Update repositories cache 'apt-get update'"
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Hello World!
      shell: echo "Hi! Tower is working!"
